### ISSUE TITLE
echarts geo maps are not working

### ISSUE THREAD

**Issue by suraj740** [sakitam-fdd/ol3Echarts#92]
Hi @sakitam-fdd , while using geo maps
 echarts.registerMap('geo', geojson)
var echartslayer = new EChartsLayer(chartOption, {forcedRerender: false,
                hideOnMoving: false,
                hideOnZooming: false,
                polyfillEvents: false,});

   getting error as :         
```
   MapDraw.js:211 Uncaught TypeError: geo.getTransformInfo is not a function
    at MapDraw.draw (MapDraw.js:211:29)
    at ExtendedClass.render (MapView.js:70:17)
    at Task.progress (Chart.js:281:20)
    at doProgress (task.js:217:11)
    at Task.taskProto.perform (task.js:157:9)
    at eval (echarts.js:1474:30)
    at ExtendedClass.eval (Global.js:517:10)
    at Array.forEach (<anonymous>)
    at each (util.js:300:9)
    at ExtendedClass.eachSeries (Global.js:514:5)
```

**Comment by sakitam-fdd** [comment]
@suraj740 geomap 类型的暂时无法支持 https://github.com/sakitam-fdd/ol3Echarts/blob/master/docs/guide/core.md#ol-echarts%E7%AE%80%E4%BB%8B
